# Generated by Django 3.1.4 on 2020-12-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="album",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="image",
            field=models.ManyToManyField(related_name="album_image", to="core.Gallery"),
        ),
    ]
