# Generated by Django 3.1.4 on 2021-01-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"ordering": ["-created"], "verbose_name_plural": "Galleries"},
        ),
        migrations.AlterField(
            model_name="gallery",
            name="images",
            field=models.ManyToManyField(to="core.Photo"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="gallery"),
        ),
    ]
