# Generated by Django 3.1.4 on 2020-12-29 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20201229_0321"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="album",
            old_name="image",
            new_name="images",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="photo",
        ),
        migrations.AddField(
            model_name="gallery",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="gallery"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gallery",
            name="title",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name="gallery",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
