# Generated by Django 3.1.4 on 2021-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210104_0751"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
