# Generated by Django 3.1.4 on 2021-01-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210109_0208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="images",
            field=models.ManyToManyField(related_name="album_image", to="core.Photo"),
        ),
    ]
