# Generated by Django 3.1.4 on 2021-01-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210109_0216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="images",
            field=models.ManyToManyField(to="core.Photo"),
        ),
    ]
