# Generated by Django 3.1.4 on 2020-12-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20201229_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="album_image", to="core.Gallery"
            ),
        ),
    ]
