# Generated by Django 3.1.4 on 2021-01-09 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210109_0218"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="images",
        ),
        migrations.AddField(
            model_name="photo",
            name="gallery",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.gallery",
            ),
            preserve_default=False,
        ),
    ]
