# Generated by Django 3.1.4 on 2021-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210104_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="slug",
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
