# Generated by Django 3.1.4 on 2021-01-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20210109_0242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
