# Generated by Django 3.1.4 on 2021-01-10 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_auto_20210110_0108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="name",
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name="photo",
            name="title",
            field=models.CharField(max_length=75),
        ),
        migrations.AlterUniqueTogether(
            name="gallery",
            unique_together={("name", "user")},
        ),
    ]
