# Generated by Django 3.1.4 on 2021-01-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20210110_0407"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gallery",
            unique_together=set(),
        ),
    ]
