# Generated by Django 3.1.4 on 2021-02-16 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20210204_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='downloads',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(choices=[('bl', 'bgc-blue text-white text-light'), ('bk', 'bgc-black text-white text-light'), ('gy', 'bgc-grey text-white text-light'), ('gn', 'bgc-green text-white text-dark'), ('yl', 'bgc-yellow text-dark text-dark'), ('rd', 'bgc-red text-white text-light'), ('lbl', 'bgc-cyan text-white text-light'), ('or', 'bgc-orange text-white text-light'), ('br', 'bgc-brown text-white text-light'), ('lbr', 'bgc-lt-brown text-white text-light'), ('pk', 'bgc-pink  text-white text-light'), ('pr', 'bgc-purple  text-white text-light')], default='gy', max_length=3),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('star', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.photo')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
