# Generated by Django 3.1.4 on 2021-02-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210216_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
