# Generated by Django 3.1.4 on 2021-02-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210216_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
