# Generated by Django 4.0.6 on 2022-07-12 03:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.IntegerField(
                        choices=[
                            (0, "general"),
                            (1, "abstract"),
                            (2, "adventure"),
                            (3, "architectural"),
                            (4, "art"),
                            (5, "black and white"),
                            (6, "business"),
                            (7, "candid"),
                            (8, "cityscape"),
                            (9, "commercial"),
                            (10, "composite"),
                            (11, "creative"),
                            (12, "documentary"),
                            (13, "drone"),
                            (14, "double-exposure"),
                            (15, "editorial"),
                            (16, "event"),
                            (17, "family"),
                            (18, "fashion"),
                            (19, "film"),
                            (20, "fine art"),
                            (21, "food"),
                            (22, "golden hour"),
                            (23, "holiday"),
                            (24, "indoor"),
                            (25, "infrared"),
                            (26, "landscape"),
                            (27, "lifestyle"),
                            (28, "long exposure"),
                            (29, "musical"),
                            (30, "milky way"),
                            (31, "minimalist"),
                            (32, "newborn"),
                            (33, "night"),
                            (34, "pet"),
                            (35, "portrait"),
                            (36, "product"),
                            (37, "real estate"),
                            (38, "seascape"),
                            (39, "social media"),
                            (40, "sports"),
                            (41, "still-life"),
                            (42, "surreal"),
                            (43, "street"),
                            (44, "time-lapse"),
                            (45, "travel"),
                            (46, "underwater"),
                            (47, "urban exploration"),
                            (48, "war"),
                            (49, "wedding"),
                            (50, "wildlife"),
                        ],
                        db_index=True,
                        default=0,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("bgc-blue text-white", "blue & white"),
                            ("bgc-black text-white", "black & white"),
                            ("bgc-grey text-white", "grey & white"),
                            ("bgc-green text-dark", "green & black"),
                            ("bgc-yellow text-dark", "yellow & black"),
                            ("bgc-red text-white", "red & white"),
                            ("bgc-cyan text-white", "light blue & white"),
                            ("bgc-orange text-white", "orange & white"),
                            ("bgc-brown text-white", "brown & white"),
                            ("bgc-lt-brown text-white", "white brown & white"),
                            ("bgc-pink text-white", "pink & white"),
                            ("bgc-purple text-white", "purple & white"),
                        ],
                        default="bgc-black text-white",
                        max_length=80,
                    ),
                ),
                ("slug", models.SlugField(editable=False)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=75, validators=[django.core.validators.MinLengthValidator(3)])),
                ("public", models.BooleanField(default=True)),
                ("slug", models.SlugField(editable=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Galleries",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(3)])),
                ("image", models.ImageField(upload_to="gallery")),
                ("is_cover", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("like", models.BooleanField(default=False)),
                ("star", models.BooleanField(default=False)),
                ("photo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="gallery.photo")),
            ],
        ),
    ]
