# Generated by Django 4.0.6 on 2022-07-12 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="user",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="gallery",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="gallery.gallery"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="gallery.tag"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="gallery", to="gallery.category"
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="gallery", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gallery",
            unique_together={("name", "user")},
        ),
    ]
