# Generated by Django 3.2.9 on 2021-11-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.CharField(
                choices=[
                    ("bgc-blue text-white text-light", "bl"),
                    ("bgc-black text-white text-light", "bk"),
                    ("bgc-grey text-white text-light", "gy"),
                    ("bgc-green text-white text-dark", "gn"),
                    ("bgc-yellow text-dark text-dark", "yl"),
                    ("bgc-red text-white text-light", "rd"),
                    ("bgc-cyan text-white text-light", "lbl"),
                    ("bgc-orange text-white text-light", "or"),
                    ("bgc-brown text-white text-light", "br"),
                    ("bgc-lt-brown text-white text-light", "lbr"),
                    ("bgc-pink  text-white text-light", "pk"),
                    ("bgc-purple  text-white text-light", "pr"),
                ],
                default="gy",
                max_length=80,
            ),
        ),
    ]
