# Generated by Django 3.2.9 on 2021-11-23 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="user",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="gallery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="gallery.gallery"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="gallery.Tag"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="category",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="gallery.category"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="gallery",
            unique_together={("name", "user")},
        ),
    ]
