# Generated by Django 3.2.9 on 2021-11-24 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="gallery",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="gallery.gallery"
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="photo",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="gallery.photo"),
        ),
    ]
