# Generated by Django 3.2.9 on 2021-11-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_category_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.CharField(
                choices=[
                    ("bgc-blue text-light", "blue & white"),
                    ("bgc-black text-light", "black & white"),
                    ("bgc-grey text-light", "grey & white"),
                    ("bgc-green text-dark", "green & black"),
                    ("bgc-yellow text-dark", "yellow & black"),
                    ("bgc-red text-light", "red & white"),
                    ("bgc-cyan text-light", "light blue & white"),
                    ("bgc-orange text-light", "orange & white"),
                    ("bgc-brown text-light", "brown & white"),
                    ("bgc-lt-brown text-light", "light brown & white"),
                    ("bgc-pink text-light", "pink & white"),
                    ("bgc-purple text-light", "purple & white"),
                ],
                default="gy",
                max_length=80,
            ),
        ),
    ]
