# Generated by Django 4.2 on 2024-12-28 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_alter_category_id_alter_gallery_id_alter_photo_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "ordering": ("-created",),
                "verbose_name": "Gallery",
                "verbose_name_plural": "Galleries",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="An ISO 8601 date time of when this was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="An ISO 8601 date time of when this was last updated",
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="An ISO 8601 date time of when this was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rate",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="An ISO 8601 date time of when this was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="An ISO 8601 date time of when this was created",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="An ISO 8601 date time of when this was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="An ISO 8601 date time of when this was created",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="An ISO 8601 date time of when this was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
