# Generated by Django 3.2.9 on 2021-12-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.CharField(
                choices=[
                    ("bgc-blue text-white", "blue & white"),
                    ("bgc-black text-white", "black & white"),
                    ("bgc-grey text-white", "grey & white"),
                    ("bgc-green text-dark", "green & black"),
                    ("bgc-yellow text-dark", "yellow & black"),
                    ("bgc-red text-white", "red & white"),
                    ("bgc-cyan text-white", "light blue & white"),
                    ("bgc-orange text-white", "orange & white"),
                    ("bgc-brown text-white", "brown & white"),
                    ("bgc-lt-brown text-white", "white brown & white"),
                    ("bgc-pink text-white", "pink & white"),
                    ("bgc-purple text-white", "purple & white"),
                ],
                default="bgc-black text-white",
                max_length=80,
            ),
        ),
    ]
