# Generated by Django 4.2 on 2024-12-28 07:32

from django.db import migrations
from gallery.enums import GalleryCategory


def forwards_func(apps, _):
    Category = apps.get_model("gallery", "Category")

    category_qs = Category.objects.all()
    category_choices = GalleryCategory.choices
    for category in category_qs:
        category.name = category_choices[int(category.name)][0]
        category.save(
            update_fields=(
                "name",
                "updated",
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_alter_category_label_alter_category_name"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop, elidable=True),
    ]
