# Generated by Django 4.2 on 2025-01-01 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery", "0006_map_old_category_to_new_enum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("GENERAL", "general"),
                    ("ABSTRACT", "abstract"),
                    ("ADVENTURE", "adventure"),
                    ("ARCHITECTURAL", "architectural"),
                    ("ART", "art"),
                    ("BLACKANDWHITE", "black and white"),
                    ("BUSINESS", "business"),
                    ("CANDID", "candid"),
                    ("CITYSCAPE", "cityscape"),
                    ("COMMERCIAL", "commercial"),
                    ("COMPOSITE", "composite"),
                    ("CREATIVE", "creative"),
                    ("DOCUMENTARY", "documentary"),
                    ("DRONE", "drone"),
                    ("DOUBLE_EXPOSURE", "double-exposure"),
                    ("EDITORIAL", "editorial"),
                    ("EVENT", "event"),
                    ("FAMILY", "family"),
                    ("FASHION", "fashion"),
                    ("FILM", "film"),
                    ("FINE_ART", "fine art"),
                    ("FOOD", "food"),
                    ("GOLDEN_HOUR", "golden hour"),
                    ("HOLIDAY", "holiday"),
                    ("INDOOR", "indoor"),
                    ("INFRARED", "infrared"),
                    ("LANDSCAPE", "landscape"),
                    ("LIFESTYLE", "lifestyle"),
                    ("LONG_EXPOSURE", "long exposure"),
                    ("MUSICAL", "musical"),
                    ("MILKYWAY", "milky way"),
                    ("MINIMALIST", "minimalist"),
                    ("NEWBORN", "newborn"),
                    ("NIGHT", "night"),
                    ("PET", "pet"),
                    ("PORTRAIT", "portrait"),
                    ("PRODUCT", "product"),
                    ("REALESTATE", "real estate"),
                    ("SEASCAPE", "seascape"),
                    ("SOCIAL_MEDIA", "social media"),
                    ("SPORTS", "sports"),
                    ("STILL_LIFE", "still-life"),
                    ("SURREAL", "surreal"),
                    ("STREET", "street"),
                    ("TIME_LAPSE", "time-lapse"),
                    ("TRAVEL", "travel"),
                    ("UNDERWATER", "underwater"),
                    ("URBAN_EXPLORATION", "urban exploration"),
                    ("WAR", "war"),
                    ("WEDDING", "wedding"),
                    ("WILDLIFE", "wildlife"),
                ],
                default="GENERAL",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="galleries",
                to="gallery.category",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
