# Generated by Django 4.2 on 2025-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_category_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
