# Generated by Django 3.2.9 on 2021-12-24 22:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalFAQ",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "question",
                    models.CharField(help_text="Frequently asked question (150 max char) required", max_length=150),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Frequently asked question's answer (500 max char) required", max_length=500
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.faqtopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical FAQ",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "question",
                    models.CharField(help_text="Frequently asked question (150 max char) required", max_length=150),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Frequently asked question's answer (500 max char) required", max_length=500
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="core.faqtopic"),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQS",
            },
        ),
    ]
