# Generated by Django 3.1.8 on 2021-10-05 10:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.IntegerField(
                        choices=[
                            (0, "general"),
                            (1, "abstract"),
                            (2, "adventure"),
                            (3, "architectural"),
                            (4, "art"),
                            (5, "black and white"),
                            (6, "business"),
                            (7, "candid"),
                            (8, "cityscape"),
                            (9, "commercial"),
                            (10, "composite"),
                            (11, "creative"),
                            (12, "documentary"),
                            (13, "drone"),
                            (14, "double-exposure"),
                            (15, "editorial"),
                            (16, "event"),
                            (17, "family"),
                            (18, "fashion"),
                            (19, "film"),
                            (20, "fine art"),
                            (21, "food"),
                            (22, "golden hour"),
                            (23, "holiday"),
                            (24, "indoor"),
                            (25, "infrared"),
                            (26, "landscape"),
                            (27, "lifestyle"),
                            (28, "long exposure"),
                            (29, "musical"),
                            (30, "milky way"),
                            (31, "minimalist"),
                            (32, "newborn"),
                            (33, "night"),
                            (34, "pet"),
                            (35, "portrait"),
                            (36, "product"),
                            (37, "real estate"),
                            (38, "seascape"),
                            (39, "social media"),
                            (40, "sports"),
                            (41, "still-life"),
                            (42, "surreal"),
                            (43, "street"),
                            (44, "time-lapse"),
                            (45, "travel"),
                            (46, "underwater"),
                            (47, "urban exploration"),
                            (48, "war"),
                            (49, "wedding"),
                            (50, "wildlife"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("bl", "bgc-blue text-white text-light"),
                            ("bk", "bgc-black text-white text-light"),
                            ("gy", "bgc-grey text-white text-light"),
                            ("gn", "bgc-green text-white text-dark"),
                            ("yl", "bgc-yellow text-dark text-dark"),
                            ("rd", "bgc-red text-white text-light"),
                            ("lbl", "bgc-cyan text-white text-light"),
                            ("or", "bgc-orange text-white text-light"),
                            ("br", "bgc-brown text-white text-light"),
                            ("lbr", "bgc-lt-brown text-white text-light"),
                            ("pk", "bgc-pink  text-white text-light"),
                            ("pr", "bgc-purple  text-white text-light"),
                        ],
                        default="gy",
                        max_length=3,
                    ),
                ),
                ("slug", models.SlugField(editable=False)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=75, validators=[django.core.validators.MinLengthValidator(3)])),
                ("public", models.BooleanField(default=True)),
                ("slug", models.SlugField(editable=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.category"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Galleries",
                "ordering": ["-created"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=75, validators=[django.core.validators.MinLengthValidator(3)])),
                ("image", models.ImageField(upload_to="gallery")),
                ("slug", models.SlugField(editable=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("gallery", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.gallery")),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("like", models.BooleanField(default=False)),
                ("star", models.BooleanField(default=False)),
                ("photo", models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to="core.photo")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.Tag"),
        ),
    ]
