# Generated by Django 4.0.6 on 2022-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="faqtopic",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="historicalfaq",
            name="id",
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
        ),
    ]
