# Generated by Django 4.2 on 2024-12-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_faq_id_alter_faqtopic_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="faqtopic",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="historicalfaq",
            name="id",
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
        ),
    ]
