# Generated by Django 4.2 on 2025-01-01 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_faq_id_alter_faqtopic_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="An ISO 8601 date time of when this was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faq",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="An ISO 8601 date time of when this was last updated",
            ),
        ),
        migrations.AddField(
            model_name="faqtopic",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="An ISO 8601 date time of when this was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faqtopic",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="An ISO 8601 date time of when this was last updated",
            ),
        ),
        migrations.AddField(
            model_name="historicalfaq",
            name="created",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="An ISO 8601 date time of when this was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalfaq",
            name="updated",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="An ISO 8601 date time of when this was last updated",
            ),
            preserve_default=False,
        ),
    ]
