# Generated by Django 3.2.9 on 2021-11-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(default="admin", editable=False),
            preserve_default=False,
        ),
    ]
