# Generated by Django 3.2.9 on 2021-11-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, help_text="user profile image ", null=True, upload_to="users"),
        ),
    ]
