# Generated by Django 4.2 on 2025-01-01 01:20

import users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.manager.UserManager()),
            ],
        ),
    ]
