# Generated by Django 3.2 on 2021-12-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
