# Generated by Django 3.2 on 2021-12-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image_url",
        ),
    ]
