from django.db import models
from django.utils.translation import gettext_lazy as _


class GalleryCategory(models.TextChoices):
    GENERAL = "GENERAL", _("general")
    ABSTRACT = "ABSTRACT", _("abstract")
    ADVENTURE = "ADVENTURE", _("adventure")
    ARCHITECTURAL = "ARCHITECTURAL", _("architectural")
    ART = "ART", _("art")
    BLACKANDWHITE = "BLACKANDWHITE", _("black and white")
    BUSINESS = "BUSINESS", _("business")
    CANDID = "CANDID", _("candid")
    CITYSCAPE = "CITYSCAPE", _("cityscape")
    COMMERCIAL = "COMMERCIAL", _("commercial")
    COMPOSITE = "COMPOSITE", _("composite")
    CREATIVE = "CREATIVE", _("creative")
    DOCUMENTARY = "DOCUMENTARY", _("documentary")
    DRONE = "DRONE", _("drone")
    DOUBLE_EXPOSURE = "DOUBLE_EXPOSURE", _("double-exposure")
    EDITORIAL = "EDITORIAL", _("editorial")
    EVENT = "EVENT", _("event")
    FAMILY = "FAMILY", _("family")
    FASHION = "FASHION", _("fashion")
    FILM = "FILM", _("film")
    FINE_ART = "FINE_ART", _("fine art")
    FOOD = "FOOD", _("food")
    GOLDEN_HOUR = "GOLDEN_HOUR", _("golden hour")
    HOLIDAY = "HOLIDAY", _("holiday")
    INDOOR = "INDOOR", _("indoor")
    INFRARED = "INFRARED", _("infrared")
    LANDSCAPE = "LANDSCAPE", _("landscape")
    LIFESTYLE = "LIFESTYLE", _("lifestyle")
    LONG_EXPOSURE = "LONG_EXPOSURE", _("long exposure")
    MUSICAL = "MUSICAL", _("musical")
    MILKYWAY = "MILKYWAY", _("milky way")
    MINIMALIST = "MINIMALIST", _("minimalist")
    NEWBORN = "NEWBORN", _("newborn")
    NIGHT = "NIGHT", _("night")
    PET = "PET", _("pet")
    PORTRAIT = "PORTRAIT", _("portrait")
    PRODUCT = "PRODUCT", _("product")
    REALESTATE = "REALESTATE", _("real estate")
    SEASCAPE = "SEASCAPE", _("seascape")
    SOCIAL_MEDIA = "SOCIAL_MEDIA", _("social media")
    SPORTS = "SPORTS", _("sports")
    STILL_LIFE = "STILL_LIFE", _("still-life")
    SURREAL = "SURREAL", _("surreal")
    STREET = "STREET", _("street")
    TIME_LAPSE = "TIME_LAPSE", _("time-lapse")
    TRAVEL = "TRAVEL", _("travel")
    UNDERWATER = "UNDERWATER", _("underwater")
    URBAN_EXPLORATION = "URBAN_EXPLORATION", _("urban exploration")
    WAR = "WAR", _("war")
    WEDDING = "WEDDING", _("wedding")
    WILDLIFE = "WILDLIFE", _("wildlife")


class GalleryCategoryColor(models.TextChoices):
    BLACK_WHITE = "bgc-black text-white", _("black & white")
    BLUE_WHITE = "bgc-blue text-white", _("blue & white")
    GREY_WHITE = "bgc-grey text-white", _("grey & white")
    RED_WHITE = "bgc-red text-white", _("red & white")
    LTBLUE_WHITE = "bgc-cyan text-white", _("light blue & white")
    ORANGO_WHITE = "bgc-orange text-white", _("orange & white")
    BROWN_WHITE = "bgc-brown text-white", _("brown & white")
    LTBROWN_WHITE = "bgc-lt-brown text-white", _("white brown & white")
    PINK_WHITE = "bgc-pink text-white", _("pink & white")
    PURPLE_WHITE = "bgc-purple text-white", _("purple & white")
    GREEN_BLACK = "bgc-green text-dark", _("green & black")
    YELLOW_BLACK = "bgc-yellow text-dark", _("yellow & black")
