name: Stage Build

on:
  workflow_dispatch:
  workflow_call:

env:
  DJANGO_IMAGE: ghcr.io/cbedroid/photo-share/django
  NGINX_IMAGE: ghcr.io/cbedroid/photo-share/nginx-proxy
  SITE_HOST: ${{ secrets.STAGE_SITE_HOST}}
  DJANGO_TAG: master

jobs:
  build:
    name: Build Django and Nginx Image For Container Registry
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Setting Django Image Tag
        run: echo "DJANGO_TAG=stage" >> $GITHUB_ENV

      - name: Building Nginx and Django Image
        run: |
          docker build -f ./django/Dockerfile.stage \
            --tag ${{ env.DJANGO_IMAGE }}:${{ env.DJANGO_TAG }} \
            ./django
          docker push ${{ env.DJANGO_IMAGE }}:${{ env.DJANGO_TAG }}

      - name: Checking Deployment Site ...
        uses: actions/checkout@v2
        if: ${{ !contains(env.SITE_HOST, 'heroku') }}
      - name: Building Nginx Image
        run: |
          echo "Builing Nginx Virtual Host"
          echo "VIRTUAL_HOST=${{ env.SITE_HOST }}" >> $GITHUB_ENV
          echo "VIRTUAL_PORT=8000" >> $GITHUB_ENV
          echo "LETSENCRYPT_HOST=${{ env.SITE_HOST }}" >> $GITHUB_ENV
          docker build \
            --tag ${{ env.NGINX_IMAGE }}:master \
            ./nginx/do-proxy
          docker push ${{ env.NGINX_IMAGE }}:master

        if: ${{ contains(env.SITE_HOST, 'heroku') }}
      - name: Ignoring Nginx Build
        run: echo "Ignoring Nginx Build  ...Deployment Site is Heroku"
  # END BUILD
